title: gbic-peer-instruction
hero_image: images/banner.png
description: gbic-peer-instruction description
version: 4
listed: false
copyedit: false
last_tested: "2020-03-13"
steps:
  - title: Introduction
  - title: Step title
  - title: What next?
